// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/api/calculator-config": {
    params: {};
  };
  "/api/create-variant": {
    params: {};
  };
  "/api/fabrics": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/button-cushion": {
    params: {};
  };
  "/app/fill-types": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/fabrics": {
    params: {};
  };
  "/app/piping": {
    params: {};
  };
  "/app/shapes": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/app/scopes_update" | "/webhooks/app/uninstalled" | "/api/calculator-config" | "/api/create-variant" | "/api/fabrics" | "/auth/login" | "/auth/*" | "/app" | "/app/button-cushion" | "/app/fill-types" | "/app/settings" | "/app/fabrics" | "/app/piping" | "/app/shapes";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/api.calculator-config.jsx": {
    id: "routes/api.calculator-config";
    page: "/api/calculator-config";
  };
  "routes/api.create-variant.jsx": {
    id: "routes/api.create-variant";
    page: "/api/create-variant";
  };
  "routes/api.fabrics.jsx": {
    id: "routes/api.fabrics";
    page: "/api/fabrics";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/button-cushion" | "/app/fill-types" | "/app/settings" | "/app/fabrics" | "/app/piping" | "/app/shapes";
  };
  "routes/app.button-cushion.jsx": {
    id: "routes/app.button-cushion";
    page: "/app/button-cushion";
  };
  "routes/app.fill-types.jsx": {
    id: "routes/app.fill-types";
    page: "/app/fill-types";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.fabrics.jsx": {
    id: "routes/app.fabrics";
    page: "/app/fabrics";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.piping.jsx": {
    id: "routes/app.piping";
    page: "/app/piping";
  };
  "routes/app.shapes.jsx": {
    id: "routes/app.shapes";
    page: "/app/shapes";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.js");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.js");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.js");
  "routes/api.calculator-config": typeof import("./app/routes/api.calculator-config.js");
  "routes/api.create-variant": typeof import("./app/routes/api.create-variant.js");
  "routes/api.fabrics": typeof import("./app/routes/api.fabrics.js");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.js");
  "routes/_index": typeof import("./app/routes/_index/route.js");
  "routes/auth.$": typeof import("./app/routes/auth.$.js");
  "routes/app": typeof import("./app/routes/app.js");
  "routes/app.button-cushion": typeof import("./app/routes/app.button-cushion.js");
  "routes/app.fill-types": typeof import("./app/routes/app.fill-types.js");
  "routes/app.settings": typeof import("./app/routes/app.settings.js");
  "routes/app.fabrics": typeof import("./app/routes/app.fabrics.js");
  "routes/app._index": typeof import("./app/routes/app._index.js");
  "routes/app.piping": typeof import("./app/routes/app.piping.js");
  "routes/app.shapes": typeof import("./app/routes/app.shapes.js");
};